### ISSUE TITLE
[Suggestion] Rep timer

### ISSUE THREAD

**Issue by williamjcm** [ReKTDevlol/NekoBot#8]
One problem with NekoBot, is that it doesn't give a timer for the rep command, unlike with the daily and card daily commands. So far, the only way to know if a user can give rep is to attempt to give some, and see if the attempt is successful or not.

![image](https://user-images.githubusercontent.com/13572456/42364104-50dd0756-80fa-11e8-9f45-87fdd12527fd.png)

Other bots like Miki, Mantaro or Tatsumaki display the time until rep becomes available again, so I think NekoBot can have the same feature.

**Comment by ReKTDevlol** [comment]
Added in commit 428a8276712c6c315578f32f5f6b7f088d0d70a6
