### ISSUE TITLE
Broken underage content filter for e621.net images

### ISSUE THREAD

**Issue by WhiteMouse1** [ReKTDevlol/NekoBot#9]
Module: nsfw.py
Lines: 392-393

Module wrongly assumes that "has_children" return by e621 API means "has underage characters in picture".
That is not correct.
"has_children", just like "children" return, refers to post's children, as in posts, which are descendants of a single parent post. This can be seen by reading through the list at https://e621.net/wiki/show/e621:api#posts_show
For example, "children" return has following description: "Comma-separated list of post IDs of this post's children"
This results in bot wrongly filtering out posts which parent other posts, while letting through undesirable content.

**Comment by ReKTDevlol** [comment]
fixed
